api_platform:
    title: 'BileMo API'
    description: "BileMo's API to access data about it's high end phones"
    version: '0.0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
